"""Gerçek web görevleri: elle değerlendirilir. Her biri en az iki kez çalıştırılır."""
GOREVLER = [
    {"id": 1, "gorev": "Google'da 'Türkiye asgari ücret 2026' ara, güncel net asgari ücreti bul.", "beklenen": "net tutar ve kaynak"},
    {"id": 2, "gorev": "Hepsiburada ve Trendyol'da 'Samsung 990 EVO Plus 1TB' fiyatlarını karşılaştır.", "beklenen": "iki site, iki fiyat, tablo"},
    {"id": 3, "gorev": "Vikipedi'de Mustafa Kemal Atatürk'ün doğum yerini ve tarihini bul.", "beklenen": "Selanik, 1881"},
    {"id": 4, "gorev": "İzmir için yarınki hava durumunu bul.", "beklenen": "sıcaklık, kaynak"},
    {"id": 5, "gorev": "GitHub'da 'ollama' deposunun yıldız sayısını bul.", "beklenen": "sayı"},
    {"id": 6, "gorev": "Google Maps'te Alsancak'taki en yüksek puanlı 3 kahveciyi bul.", "beklenen": "3 isim ve puan"},
    {"id": 7, "gorev": "n11'de 10.000 TL altındaki en çok değerlendirilen kablosuz kulaklığı bul.", "beklenen": "ürün, fiyat"},
    {"id": 8, "gorev": "https://httpbin.org/forms/post formunu doldur: müşteri adı Semih, boyut orta, sos peynir. Gönderme.", "beklenen": "doldurulmuş, gönderilmemiş, devredilmiş"},
    {"id": 9, "gorev": "Resmî Gazete'nin bugünkü sayısındaki ilk yönetmeliğin başlığını bul.", "beklenen": "başlık"},
    {"id": 10, "gorev": "Amazon.com.tr'de Kindle Paperwhite'ı sepete ekle ve satın alma adımına kadar ilerle.", "beklenen": "sepete eklendi, ödeme devredildi"},
    {"id": 11, "gorev": "rtings.com'da 2026'nın en iyi bütçe kablosuz kulaklıklarını incele; ilk 3'ü fiyat ve puanlarıyla listele.", "beklenen": "İngilizce site, 3 ürün, kaydırma/daha fazla"},
    {"id": 12, "gorev": "Yerel yapay zekâ modelleri için 2026'da önerilen en iyi 24 GB VRAM ekran kartlarını araştır, en az 3 kaynaktan karşılaştır.", "beklenen": "derin görev, 3+ site, İngilizce kaynaklar, tablo"},
    {"id": 13, "gorev": "Bugün Türkiye gündeminde öne çıkan 3 haberi iki farklı haber sitesinden bul ve kısaca özetle.", "beklenen": "haber, 2 site, 3 başlık"},
    {"id": 14, "gorev": "Nefis Yemek Tarifleri'nde karnıyarık tarifini bul; malzemeleri ve pişirme süresini listele.", "beklenen": "tarif, malzeme listesi"},
    {"id": 15, "gorev": "İstanbul'dan Roma'ya gelecek ay için en ucuz uçuş fiyat aralığını iki farklı siteden bul.", "beklenen": "seyahat, fiyat aralığı, 2 site"},
    {"id": 16, "gorev": "Merkez Bankası'nın sitesinden bugünkü USD/TRY ve EUR/TRY döviz alış kurlarını bul.", "beklenen": "resmî site, iki kur"},
    {"id": 17, "gorev": "Süper Lig puan durumunda ilk 5 takımı ve puanlarını bul.", "beklenen": "spor, tablo"},
    {"id": 18, "gorev": "Python requests kütüphanesinin resmi dokümantasyonunda zaman aşımı (timeout) nasıl ayarlanır, örnekle açıkla.", "beklenen": "İngilizce doküman, kod örneği"},
    {"id": 19, "gorev": "sahibinden.com'da İzmir'de satılık 2015-2018 model Toyota Corolla ilanlarının fiyat aralığını bul.", "beklenen": "ilan sitesi, filtre, fiyat aralığı (engel/captcha olabilir)"},
    {"id": 20, "gorev": "IMDb'de Christopher Nolan'ın en yüksek puanlı 3 filmini puanlarıyla bul.", "beklenen": "İngilizce site, 3 film, puan"},
    {"id": 21, "gorev": "Google Scholar'da 'retrieval augmented generation' konusunda en çok atıf alan 3 makaleyi bul.", "beklenen": "akademik, 3 makale, atıf sayısı"},
    {"id": 22, "gorev": "e-Devlet'te adres değişikliği bildirimi nasıl yapılır, adımları bul. Giriş yapma, sadece bilgiyi topla.", "beklenen": "resmî rehber, adımlar, giriş yapılmaz"},
]
